Makefile: remove the separate test.c target to fix a build failure
Compared to the other build targets, test.c has -fno-strict-overflow but
lacks the following CFLAGS: -fPIC -fno-stack-protector -fgnu89-inline .
And the lack of -fno-stack-protector flag is causing a build failure:

ld: test.o: in function `L24':
test.c:(.text+0xb40): undefined reference to `__stack_chk_fail_local'

The need for a separate test.c target is not clear, and - unlike 5.01 -
the 5.31b Makefile does not have it anymore, so lets remove it.